-- Minimal schema for core ERP/POS features (no comments in statements)

CREATE TABLE IF NOT EXISTS Companies (
  CompanyID BIGINT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(200) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Employees (
  EmployeeID BIGINT AUTO_INCREMENT PRIMARY KEY,
  CompanyID BIGINT NOT NULL,
  FirstName VARCHAR(100) NOT NULL,
  LastName VARCHAR(100) NULL,
  Email VARCHAR(200) UNIQUE,
  Pin VARCHAR(20) NULL,
  IsAdmin TINYINT(1) NOT NULL DEFAULT 0,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT FK_Employees_Company FOREIGN KEY (CompanyID) REFERENCES Companies(CompanyID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Customers (
  CustomerID BIGINT AUTO_INCREMENT PRIMARY KEY,
  CompanyID BIGINT NOT NULL,
  CustomerName VARCHAR(200) NOT NULL,
  Email VARCHAR(200) NULL,
  TaxID VARCHAR(50) NULL,
  GroupName VARCHAR(100) NULL,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT FK_Customers_Company FOREIGN KEY (CompanyID) REFERENCES Companies(CompanyID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Categories (
  CategoryID BIGINT AUTO_INCREMENT PRIMARY KEY,
  CompanyID BIGINT NOT NULL,
  CategoryName VARCHAR(200) NOT NULL,
  CONSTRAINT FK_Categories_Company FOREIGN KEY (CompanyID) REFERENCES Companies(CompanyID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Brands (
  BrandID BIGINT AUTO_INCREMENT PRIMARY KEY,
  CompanyID BIGINT NOT NULL,
  BrandName VARCHAR(200) NOT NULL,
  CONSTRAINT FK_Brands_Company FOREIGN KEY (CompanyID) REFERENCES Companies(CompanyID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS TaxRates (
  TaxRateID BIGINT AUTO_INCREMENT PRIMARY KEY,
  CompanyID BIGINT NOT NULL,
  Name VARCHAR(100) NOT NULL,
  Rate DECIMAL(10,4) NOT NULL DEFAULT 0,
  IsDefault TINYINT(1) NOT NULL DEFAULT 0,
  CONSTRAINT FK_TaxRates_Company FOREIGN KEY (CompanyID) REFERENCES Companies(CompanyID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Warehouses (
  WarehouseID BIGINT AUTO_INCREMENT PRIMARY KEY,
  CompanyID BIGINT NOT NULL,
  WarehouseName VARCHAR(200) NOT NULL,
  CONSTRAINT FK_Warehouses_Company FOREIGN KEY (CompanyID) REFERENCES Companies(CompanyID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Products (
  ProductID BIGINT AUTO_INCREMENT PRIMARY KEY,
  CompanyID BIGINT NOT NULL,
  ProductName VARCHAR(200) NOT NULL,
  SKU VARCHAR(100) UNIQUE,
  Barcode VARCHAR(100),
  CategoryID BIGINT NULL,
  BrandID BIGINT NULL,
  TaxRateID BIGINT NULL,
  Price DECIMAL(18,4) NOT NULL DEFAULT 0,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT FK_Products_Company FOREIGN KEY (CompanyID) REFERENCES Companies(CompanyID),
  CONSTRAINT FK_Products_Category FOREIGN KEY (CategoryID) REFERENCES Categories(CategoryID),
  CONSTRAINT FK_Products_Brand FOREIGN KEY (BrandID) REFERENCES Brands(BrandID),
  CONSTRAINT FK_Products_TaxRate FOREIGN KEY (TaxRateID) REFERENCES TaxRates(TaxRateID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PriceLists (
  PriceListID BIGINT AUTO_INCREMENT PRIMARY KEY,
  CompanyID BIGINT NOT NULL,
  Name VARCHAR(200) NOT NULL,
  Currency VARCHAR(10) NULL,
  IsDefault TINYINT(1) NOT NULL DEFAULT 0,
  CONSTRAINT FK_PriceLists_Company FOREIGN KEY (CompanyID) REFERENCES Companies(CompanyID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS PriceListItems (
  PriceListItemID BIGINT AUTO_INCREMENT PRIMARY KEY,
  PriceListID BIGINT NOT NULL,
  ProductID BIGINT NOT NULL,
  Price DECIMAL(18,4) NOT NULL DEFAULT 0,
  CONSTRAINT FK_PriceListItems_List FOREIGN KEY (PriceListID) REFERENCES PriceLists(PriceListID),
  CONSTRAINT FK_PriceListItems_Product FOREIGN KEY (ProductID) REFERENCES Products(ProductID),
  CONSTRAINT UQ_PriceList_Product UNIQUE (PriceListID, ProductID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Promotions (
  PromotionID BIGINT AUTO_INCREMENT PRIMARY KEY,
  CompanyID BIGINT NOT NULL,
  Name VARCHAR(200) NOT NULL,
  Code VARCHAR(100) NULL UNIQUE,
  Description TEXT NULL,
  Type ENUM('percent','amount','bogo','bundle','shipping') NOT NULL DEFAULT 'percent',
  Value DECIMAL(18,4) NOT NULL DEFAULT 0,
  UnitPrice DECIMAL(18,4) NULL,
  Enabled TINYINT(1) NOT NULL DEFAULT 1,
  Stackable TINYINT(1) NOT NULL DEFAULT 1,
  Priority INT NOT NULL DEFAULT 100,
  MinQuantity INT NULL,
  PerOrderLimit INT NULL,
  PerCustomerLimit INT NULL,
  TotalRedemptions INT NULL,
  StartAt DATETIME NULL,
  EndAt DATETIME NULL,
  Timezone VARCHAR(100) NULL,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UpdatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT FK_Promotions_Company FOREIGN KEY (CompanyID) REFERENCES Companies(CompanyID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS Promotion_Scopes (
  ScopeID BIGINT AUTO_INCREMENT PRIMARY KEY,
  PromotionID BIGINT NOT NULL,
  ScopeType ENUM('category','product','brand','customer','employee','custom_field','channel','day') NOT NULL,
  ScopeValue VARCHAR(255) NOT NULL,
  CONSTRAINT FK_Scopes_Promo FOREIGN KEY (PromotionID) REFERENCES Promotions(PromotionID) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ProductCustomFieldDefinitions (
  ProductCustomFieldDefinitionID INT AUTO_INCREMENT PRIMARY KEY,
  CompanyID BIGINT NOT NULL,
  FieldName VARCHAR(255) NOT NULL,
  DataType ENUM('Text','Number','Boolean','Date','JSON','Select') NOT NULL DEFAULT 'Text',
  IsActive TINYINT(1) NOT NULL DEFAULT 1,
  CONSTRAINT FK_CFDefs_Company FOREIGN KEY (CompanyID) REFERENCES Companies(CompanyID),
  CONSTRAINT UQ_CFDefs_Name UNIQUE (CompanyID, FieldName)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS ProductCustomFieldOptions (
  OptionID INT AUTO_INCREMENT PRIMARY KEY,
  ProductCustomFieldDefinitionID INT NOT NULL,
  OptionValue VARCHAR(255) NOT NULL,
  CONSTRAINT FK_CFOpts_Def FOREIGN KEY (ProductCustomFieldDefinitionID) REFERENCES ProductCustomFieldDefinitions(ProductCustomFieldDefinitionID) ON DELETE CASCADE,
  CONSTRAINT UQ_CFOpts UNIQUE (ProductCustomFieldDefinitionID, OptionValue)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS SalesTickets (
  TicketID BIGINT AUTO_INCREMENT PRIMARY KEY,
  CompanyID BIGINT NOT NULL,
  CustomerID BIGINT NULL,
  WarehouseID BIGINT NULL,
  DocumentType VARCHAR(50) NOT NULL DEFAULT 'TICKET',
  ItemsJSON LONGTEXT NOT NULL,
  ReadyForBilling TINYINT(1) NOT NULL DEFAULT 0,
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT FK_Tickets_Company FOREIGN KEY (CompanyID) REFERENCES Companies(CompanyID),
  CONSTRAINT FK_Tickets_Customer FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID),
  CONSTRAINT FK_Tickets_Warehouse FOREIGN KEY (WarehouseID) REFERENCES Warehouses(WarehouseID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
